# Generated by Django 2.0.3 on 2018-04-20 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee_Scolaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Annee', models.DateField()),
                ('Specialite', models.CharField(max_length=30)),
                ('Moy_G', models.FloatField()),
                ('Moy_S1', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Encadreur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=30)),
                ('Date_De_Naissance', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Ntel', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Description', models.CharField(max_length=300)),
                ('Logo', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('P_Couverture', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=30)),
                ('Date_De_Naissance', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Annee_Scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Annee_Scolaire')),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Frais_De_Dejeuner', models.FloatField()),
                ('Frais_De_Diner', models.FloatField()),
                ('Frais_Dhebergement', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Etat', models.CharField(default='en cour', max_length=30)),
                ('Date_debut', models.DateField()),
                ('Date_fin', models.DateField()),
                ('Type_De_Stage', models.CharField(max_length=30)),
                ('Encadreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Encadreur')),
                ('Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Etudiant')),
                ('Payement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Payement')),
                ('Raport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Raport')),
            ],
        ),
        migrations.CreateModel(
            name='Stage_Propose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Durée', models.IntegerField()),
                ('theme', models.CharField(max_length=30)),
                ('Date_limite', models.DateField()),
                ('Entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Suivi_Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assiduité', models.IntegerField()),
                ('Remarque', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='Stage_Propose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Stage_Propose'),
        ),
        migrations.AddField(
            model_name='stage',
            name='Suivi_Stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Suivi_Stage'),
        ),
    ]
