# Generated by Django 2.0.3 on 2018-04-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='Adresse',
        ),
        migrations.AddField(
            model_name='adresse',
            name='Etudiant',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='administration.Etudiant'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='Logo',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='P_Couverture',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='stage_propose',
            name='Durée',
            field=models.IntegerField(),
        ),
    ]
